<?php

$airija = [
    'Dublin',
    'Cork',
    'Limerick',
    'Galway',
    'Waterford',
    'Drogheda',
    'Kilkenny',
    'Sligo',
    'Wexford',
    'Clonmel',
    'Dundalk',
    'Bray',
    'Navan',
    'Ennis',
    'Tralee',
    'Carlow',
    'Naas',
    'Athlone',
    'Letterkenny',
    'Tullamore',
    'Killarney',
    'Arklow',
    'Castlebar',
    'Mallow',
    'Ballina',
    'Athy',
    'Longford',
    'Dungarvan',
    'Nenagh',
    'Thurles',
    'Youghall',
    'Monaghan',
    'Ballinasloe',
    'Newbridge',
    'Mullingar',
    'Balbriggan',
    'Greystones',
    'Leixlip',
    'Tramore',
    'Shannon',
    'Edenderry'
];

$anglija = [
    'London',
    'Birmingham',
    'Leeds',
    'Glasgow',
    'Sheffield',
    'Bradford',
    'Liverpool',
    'Edinburgh',
    'Manchester',
    'Bristol',
    'Kirklees',
    'Fife',
    'Wirral',
    'North Lanarkshire',
    'Wakefield',
    'Cardiff',
    'Dudley',
    'Wigan',
    'East Riding',
    'South Lanarkshire',
    'Coventry',
    'Belfast',
    'Leicester',
    'Sunderland',
    'Sandwell',
    'Doncaster',
    'Stockport',
    'Sefton',
    'Nottingham',
    'Newcastle-upon-Tyne',
    'Kingston-upon-Hull',
    'Bolton',
    'Walsall',
    'Plymouth',
    'Rotherham',
    'Stoke-on-Trent',
    'Wolverhampton',
    'Rhondda Cynon Taff',
    'South Gloucestershire',
    'Derby',
    'Swansea',
    'Salford',
    'Aberdeenshire',
    'Barnsley',
    'Tameside',
    'Oldham',
    'Trafford',
    'Aberdeen',
    'Southampton',
    'Highland',
    'Rochdale',
    'Solihull',
    'Gateshead',
    'Milton Keynes',
    'North Tyneside',
    'Calderdale',
    'Northampton',
    'Portsmouth',
    'Warrington',
    'North Somerset',
    'Bury',
    'Luton',
    'St Helens',
    'Stockton-on-Tees',
    'Renfrewshire',
    'York',
    'Thamesdown',
    'Southend-on-Sea',
    'New Forest',
    'Caerphilly',
    'Carmarthenshire',
    'Bath & North East Somerset',
    'Wycombe',
    'Basildon',
    'Bournemouth',
    'Peterborough',
    'North East Lincolnshire',
    'Chelmsford',
    'Brighton',
    'South Tyneside',
    'Charnwood',
    'Aylesbury Vale',
    'Colchester',
    'Knowsley',
    'North Lincolnshire',
    'Huntingdonshire',
    'Macclesfield',
    'Blackpool',
    'West Lothian',
    'South Somerset',
    'Dundee',
    'Basingstoke & Deane',
    'Harrogate',
    'Dumfries & Galloway',
    'Middlesbrough',
    'Flintshire',
    'Rochester-upon-Medway',
    'The Wrekin',
    'Newbury',
    'Falkirk',
    'Reading',
    'Wokingham',
    'Windsor & Maidenhead',
    'Maidstone',
    'Redcar & Cleveland',
    'North Ayrshire',
    'Blackburn',
    'Neath Port Talbot',
    'Poole',
    'Wealden',
    'Arun',
    'Bedford',
    'Oxford',
    'Lancaster',
    'Newport',
    'Canterbury',
    'Preston',
    'Dacorum',
    'Cherwell',
    'Perth & Kinross',
    'Thurrock',
    'Tendring',
    'Kings Lynn & West Norfolk',
    'St Albans',
    'Bridgend',
    'South Cambridgeshire',
    'Braintree',
    'Norwich',
    'Thanet',
    'Isle of Wight',
    'Mid Sussex',
    'South Oxfordshire',
    'Guildford',
    'Elmbridge',
    'Stafford',
    'Powys',
    'East Hertfordshire',
    'Torbay',
    'Wrexham Maelor',
    'East Devon',
    'East Lindsey',
    'Halton',
    'Warwick',
    'East Ayrshire',
    'Newcastle-under-Lyme',
    'North Wiltshire',
    'South Kesteven',
    'Epping Forest',
    'Vale of Glamorgan',
    'Reigate & Banstead',
    'Chester',
    'Mid Bedfordshire',
    'Suffolk Coastal',
    'Horsham',
    'Nuneaton & Bedworth',
    'Gwynedd',
    'Swale',
    'Havant & Waterloo',
    'Teignbridge',
    'Cambridge',
    'Vale Royal',
    'Amber Valley',
    'North Hertfordshire',
    'South Ayrshire',
    'Waverley',
    'Broadland',
    'Crewe & Nantwich',
    'Breckland',
    'Ipswich',
    'Pembrokeshire',
    'Vale of White Horse',
    'Salisbury',
    'Gedling',
    'Eastleigh',
    'Broxtowe',
    'Stratford-on-Avon',
    'South Bedfordshire',
    'Angus',
    'East Hampshire',
    'East Dunbartonshire',
    'Conway',
    'Sevenoaks',
    'Slough',
    'Bracknell Forest',
    'West Lancashire',
    'West Wiltshire',
    'Ashfield',
    'Lisburn',
    'n/aScarborough',
    'Stroud',
    'Wychavon',
    'Waveney',
    'Exeter',
    'Dover',
    'Test Valley',
    'Gloucester',
    'Erewash',
    'Cheltenham',
    'Bassetlaw',
    'Scottish Borders',
    'Arklow',
    'Castlebar',
    'Mallow',
    'Ballina',
    'Athy',
    'Longford',
    'Dungarvan',
    'Nenagh',
    'Thurles',
    'Youghall',
    'Monaghan',
    'Ballinasloe',
    'Newbridge',
    'Mullingar',
    'Balbriggan',
    'Greystones',
    'Leixlip',
    'Tramore',
    'Shannon',
    'Edenderry',
];

$list = array(
    'London', 
    'Birmingham', 
    'Leeds', 
    'Glasgow', 
    'Sheffield', 
    'Bradford', 
    'Liverpool', 
    'Edinburgh', 
    'Manchester', 
    'Bristol', 
    'Kirklees', 
    'Fife', 
    'Wirral', 
    'North Lanarkshire', 
    'Wakefield', 
    'Cardiff', 
    'Dudley', 
    'Wigan', 
    'East Riding', 
    'South Lanarkshire', 
    'Coventry', 
    'Belfast', 
    'Leicester', 
    'Sunderland', 
    'Sandwell', 
    'Doncaster', 
    'Stockport', 
    'Sefton', 
    'Nottingham', 
    'Newcastle-upon-Tyne', 
    'Kingston-upon-Hull', 
    'Bolton', 
    'Walsall', 
    'Plymouth', 
    'Rotherham', 
    'Stoke-on-Trent', 
    'Wolverhampton', 
    'Rhondda Cynon Taff', 
    'South Gloucestershire', 
    'Derby', 
    'Swansea', 
    'Salford', 
    'Aberdeenshire', 
    'Barnsley', 
    'Tameside', 
    'Oldham', 
    'Trafford', 
    'Aberdeen', 
    'Southampton', 
    'Highland', 
    'Rochdale', 
    'Solihull', 
    'Gateshead', 
    'Milton Keynes', 
    'North Tyneside', 
    'Calderdale', 
    'Northampton', 
    'Portsmouth', 
    'Warrington', 
    'North Somerset', 
    'Bury', 
    'Luton', 
    'St Helens', 
    'Stockton-on-Tees', 
    'Renfrewshire', 
    'York', 
    'Thamesdown', 
    'Southend-on-Sea', 
    'New Forest', 
    'Caerphilly', 
    'Carmarthenshire', 
    'Bath &amp; North East Somerset', 
    'Wycombe', 
    'Basildon', 
    'Bournemouth', 
    'Peterborough', 
    'North East Lincolnshire', 
    'Chelmsford', 
    'Brighton', 
    'South Tyneside', 
    'Charnwood', 
    'Aylesbury Vale', 
    'Colchester', 
    'Knowsley', 
    'North Lincolnshire', 
    'Huntingdonshire', 
    'Macclesfield', 
    'Blackpool', 
    'West Lothian', 
    'South Somerset', 
    'Dundee', 
    'Basingstoke &amp; Deane', 
    'Harrogate', 
    'Dumfries &amp; Galloway', 
    'Middlesbrough', 
    'Flintshire', 
    'Rochester-upon-Medway', 
    'The Wrekin', 
    'Newbury', 
    'Falkirk', 
    'Reading', 
    'Wokingham', 
    'Windsor &amp; Maidenhead', 
    'Maidstone', 
    'Redcar &amp; Cleveland', 
    'North Ayrshire', 
    'Blackburn', 
    'Neath Port Talbot', 
    'Poole', 
    'Wealden', 
    'Arun', 
    'Bedford', 
    'Oxford', 
    'Lancaster', 
    'Newport', 
    'Canterbury', 
    'Preston', 
    'Dacorum', 
    'Cherwell', 
    'Perth &amp; Kinross', 
    'Thurrock', 
    'Tendring', 
    'Kings Lynn &amp; West Norfolk', 
    'St Albans', 
    'Bridgend', 
    'South Cambridgeshire', 
    'Braintree', 
    'Norwich', 
    'Thanet', 
    'Isle of Wight', 
    'Mid Sussex', 
    'South Oxfordshire', 
    'Guildford', 
    'Elmbridge', 
    'Stafford', 
    'Powys', 
    'East Hertfordshire', 
    'Torbay', 
    'Wrexham Maelor', 
    'East Devon', 
    'East Lindsey', 
    'Halton', 
    'Warwick', 
    'East Ayrshire', 
    'Newcastle-under-Lyme', 
    'North Wiltshire', 
    'South Kesteven', 
    'Epping Forest', 
    'Vale of Glamorgan', 
    'Reigate &amp; Banstead', 
    'Chester', 
    'Mid Bedfordshire', 
    'Suffolk Coastal', 
    'Horsham', 
    'Nuneaton &amp; Bedworth', 
    'Gwynedd', 
    'Swale', 
    'Havant &amp; Waterloo', 
    'Teignbridge', 
    'Cambridge', 
    'Vale Royal', 
    'Amber Valley', 
    'North Hertfordshire', 
    'South Ayrshire', 
    'Waverley', 
    'Broadland', 
    'Crewe &amp; Nantwich', 
    'Breckland', 
    'Ipswich', 
    'Pembrokeshire', 
    'Vale of White Horse', 
    'Salisbury', 
    'Gedling', 
    'Eastleigh', 
    'Broxtowe', 
    'Stratford-on-Avon', 
    'South Bedfordshire', 
    'Angus', 
    'East Hampshire', 
    'East Dunbartonshire', 
    'Conway', 
    'Sevenoaks', 
    'Slough', 
    'Bracknell Forest', 
    'West Lancashire', 
    'West Wiltshire', 
    'Ashfield', 
    'Lisburn', 
    'n/aScarborough', 
    'Stroud', 
    'Wychavon', 
    'Waveney', 
    'Exeter', 
    'Dover', 
    'Test Valley', 
    'Gloucester', 
    'Erewash', 
    'Cheltenham', 
    'Bassetlaw', 
    'Scottish Borders',
    'Dublin',
    'Cork',
    'Limerick',
    'Galway',
    'Waterford',
    'Drogheda',
    'Kilkenny',
    'Sligo',
    'Wexford',
    'Clonmel',
    'Dundalk',
    'Bray',
    'Navan',
    'Ennis',
    'Tralee',
    'Carlow',
    'Naas',
    'Athlone',
    'Letterkenny',
    'Tullamore',
    'Killarney',
    'Arklow',
    'Castlebar',
    'Mallow',
    'Ballina',
    'Athy',
    'Longford',
    'Dungarvan',
    'Nenagh',
    'Thurles',
    'Youghall',
    'Monaghan',
    'Ballinasloe',
    'Newbridge',
    'Mullingar',
    'Balbriggan',
    'Greystones',
    'Leixlip',
    'Tramore',
    'Shannon',
    'Edenderry',
);

$rajonai = array(
    "E1: Mile End, Stepney, Whitechapel",
    "E2: Bethnal Green, Shoreditch",
    "E3: Bow, Bromley-by-Bow",
    "E4: Chingford, Highams Park",
    "E5: Clapton",
    "E6: East Ham, Beckton",
    "E7: Forest Gate, Upton Park",
    "E8: Hackney, Dalston",
    "E9: Hackney, Homerton",
    "E10: Leyton",
    "E11: Leytonstone",
    "E12: Manor Park",
    "E13: Plaistow",
    "E14: Isle of Dogs, Millwall, Poplar",
    "E15: Stratford, West Ham",
    "E16: Canning Town, North Woolwich",
    "E17: Walthamstow",
    "E18: South Woodford",
    "E20: Olympic Park, Stratford",
    "N1: Barnsbury, Canonbury, Islington",
    "N2: East Finchley",
    "N3: Finchley Central",
    "N4: Finsbury Park, Manor House",
    "N5: Highbury",
    "N6: Highgate",
    "N7: Holloway",
    "N8: Crouch End, Hornsey",
    "N9: Lower Edmonton",
    "N10: Muswell Hill",
    "N11: Friern Barnet, New Southgate",
    "N12: North Finchley, Woodside Park",
    "N13: Palmers Green",
    "N14: Southgate",
    "N15: Seven Sisters",
    "N16: Stamford Hill, Stoke Newington",
    "N17: Tottenham",
    "N18: Upper Edmonton",
    "N19: Archway, Tufnell Park",
    "N20: Totteridge, Whetstone",
    "N21: Winchmore Hill",
    "N22: Alexandra Palace, Wood Green",
    "NW1: Camden Town, Regent's Park",
    "NW2: Cricklewood, Neasden",
    "NW3: Hampstead, Swiss Cottage",
    "NW4: Brent Cross, Hendon",
    "NW5: Kentish Town",
    "NW6: Kilburn, Queens Park, West Hampstead",
    "NW7: Mill Hill",
    "NW8: St John's Wood",
    "NW9: Colindale, Kingsbury",
    "NW10: Harlesden, Kensal Green, Willesden",
    "NW11: Golders Green, Hampstead Garden Suburb",
    "SE1: Bermondsey, Borough, Southwark, Waterloo",
    "SE2: Abbey Wood",
    "SE3: Blackheath, Westcombe Park",
    "SE4: Brockley, Crofton Park, Honor Oak Park",
    "SE5: Camberwell",
    "SE6: Bellingham, Catford, Hither Green",
    "SE7: Charlton",
    "SE8: Deptford",
    "SE9: Eltham, Mottingham",
    "SE10: Greenwich",
    "SE11: Lambeth",
    "SE12: Grove Park, Lee",
    "SE13: Hither Green, Lewisham",
    "SE14: New Cross, New Cross Gate",
    "SE15: Nunhead, Peckham",
    "SE16: Rotherhithe, South Bermondsey, Surrey Docks",
    "SE17: Elephant & Castle, Walworth",
    "SE18: Plumstead, Woolwich",
    "SE19: Crystal Palace, Upper Norwood",
    "SE20: Anerley, Penge",
    "SE21: Dulwich",
    "SE22: East Dulwich",
    "SE23: Forest Hill",
    "SE24: Herne Hill",
    "SE25: South Norwood",
    "SE26: Sydenham",
    "SE27: Tulse Hill, West Norwood",
    "SE28: Thamesmead",
    "SW1: Belgravia, Pimlico, Westminster",
    "SW2: Brixton, Streatham Hill",
    "SW3: Brompton, Chelsea",
    "SW4: Clapham",
    "SW5: Earl's Court",
    "SW6: Fulham, Parson's Green",
    "SW7: South Kensington",
    "SW8: Nine Elms, South Lambeth",
    "SW9: Brixton, Stockwell",
    "SW10: West Brompton, World's End",
    "SW11: Battersea, Clapham Junction",
    "SW12: Balham",
    "SW13: Barnes, Castelnau",
    "SW14: East Sheen, Mortlake",
    "SW15: Putney, Roehampton",
    "SW16: Norbury, Streatham",
    "SW17: Tooting",
    "SW18: Earlsfield, Wandsworth",
    "SW19: Merton, Wimbledon",
    "SW20: Raynes Park, South Wimbledon",
    "W1: Marylebone, Mayfair, Soho",
    "W2: Bayswater, Paddington",
    "W3: Acton",
    "W4: Chiswick",
    "W5: Ealing",
    "W6: Hammersmith",
    "W7: Hanwell",
    "W8: Kensington",
    "W9: Maida Vale, Warwick Avenue",
    "W10: Ladbroke Grove, North Kensington",
    "W11: Holland Park, Notting Hill",
    "W12: Shepherd's Bush",
    "W13: West Ealing",
    "W14: West Kensington",
    "Outer London",
    "BR: Bromley",
    "CR: Croydon",
    "DA: Dartford",
    "EN: Enfield",
    "HA: Harrow",
    "IG: Ilford",
    "KT: Kingston",
    "RM: Romford",
    "SM: Sutton",
    "TW: Twickenham",
    "UB: Uxbridge",
    "WD: Watford",
);

//////
$gimtoji_salis = array(
    "Abchazija",
    "Afganistanas",
    "Airija",
    "Alandai",
    "Albanija",
    "Alžyras",
    "Amerikos Samoa",
    "Andora",
    "Angilija",
    "Angola",
    "Antarktida",
    "Antigva ir Barbuda",
    "Argentina",
    "Armėnija",
    "Aruba",
    "Australija",
    "Austrija",
    "Azerbaidžanas",
    "Azorai",
    "Bahamos",
    "Bahreinas",
    "Baltarusija",
    "Bangladešas",
    "Barbadosas",
    "Belgija",
    "Belizas",
    "Beninas",
    "Bermuda",
    "Bisau Gvinėja",
    "Bolivija",
    "Bosnija ir Hercegovina",
    "Botsvana",
    "Brazilija",
    "Brunėjus",
    "Bulgarija",
    "Burkina Fasas",
    "Burundis",
    "Buvė",
    "Butanas",
    "Centrinės Afrikos Respublika",
    "Čadas",
    "Čekija",
    "Čilė",
    "Danija",
    "Didžiosios Britanijos Mergelių salos",
    "Dominika",
    "Dominikos Respublika",
    "Dramblio Kaulo Krantas",
    "Džersis",
    "Džibutis",
    "Egiptas",
    "Ekvadoras",
    "Eritrėja",
    "Estija",
    "Etiopija",
    "Falklando salos",
    "Farerų salos",
    "Fidžis",
    "Filipinai",
    "Gabonas",
    "Gajana",
    "Gambija",
    "Gana",
    "Gernsis",
    "Gibraltaras",
    "Graikija",
    "Grenada",
    "Grenlandija",
    "Gruzija",
    "Guamas",
    "Gvadelupa",
    "Gvatemala",
    "Gvinėja",
    "Haitis",
    "Herdo ir Makdonaldo salos",
    "Hondūras",
    "Honkongas",
    "Indija",
    "Indijos vandenyno britų salos",
    "Indonezija",
    "Irakas",
    "Iranas",
    "Islandija",
    "Ispanija",
    "Italija",
    "Izraelis",
    "Jamaika",
    "Japonija",
    "Jemenas",
    "Jordanija",
    "Jungtiniai Arabų Emyratai",
    "Jungtinė Karalystė",
    "JAV",
    "Juodkalnija",
    "Kaimanų salos",
    "Kalėdų sala",
    "Kalnų Karabachas",
    "Kambodža",
    "Kamerūnas",
    "Kanada",
    "Kataras",
    "Kazachija",
    "Kenija",
    "Kinija",
    "Kipras",
    "Kirgizija",
    "Kiribatis",
    "Kokosų salos",
    "Kolumbija",
    "Komorai",
    "Kongo Demokratinė Respublika",
    "Kongas",
    "Kosovas",
    "Kosta Rika",
    "Kroatija",
    "Kuba",
    "Kuko salos",
    "Kuveitas",
    "Laosas",
    "Latvija",
    "Lenkija",
    "Lesotas",
    "Libanas",
    "Liberija",
    "Libija",
    "Lichtenšteinas",
    "Lietuva",
    "Liuksemburgas",
    "Majotas",
    "Makao",
    "Madagaskaras",
    "Makedonija",
    "Malaizija",
    "Malavis",
    "Maldyvai",
    "Malis",
    "Malta",
    "Marianos šiaurinės salos",
    "Marokas",
    "Martinika",
    "Maršalo salos",
    "Mauricijus",
    "Mauritanija",
    "Meksika",
    "Meno sala",
    "Mergelių salos (JAV)",
    "Mianmaras",
    "Mikronezijos Federacinės Valstijos",
    "Moldavija",
    "Monakas",
    "Mongolija",
    "Montseratas",
    "Mozambikas",
    "Namibija",
    "Naujoji Kaledonija",
    "Naujoji Zelandija",
    "Nauru",
    "Nepalas",
    "Nyderlandai",
    "Nyderlandų Antilai",
    "Nigerija",
    "Nigeris",
    "Nikaragva",
    "Niujė",
    "Norfolkas",
    "Norvegija",
    "Omanas",
    "Padniestrė",
    "Pakistanas",
    "Palau",
    "Palestina",
    "Panama",
    "Papua Naujoji Gvinėja",
    "Paragvajus",
    "Peru",
    "Pietų Afrikos Respublika",
    "Pietų Džordžija ir Pietų Sandvičo salos",
    "Pietų Korėja",
    "Pietų Osetija",
    "Pitkerno salos",
    "Portugalija",
    "Prancūzijos Gviana",
    "Prancūzijos Polinezija",
    "Prancūzija",
    "Prancūzijos Pietų ir Antarkties sritys",
    "Puerto Rikas",
    "Pusiaujo Gvinėja",
    "Reunionas",
    "Ruanda",
    "Rumunija",
    "Rusija",
    "Rytų Timoras",
    "Saliamono salos",
    "Salvadoras",
    "Samoa",
    "San Marinas",
    "San Tomė ir Prinsipė",
    "Saudo Arabija",
    "Seišeliai",
    "Sen Pjeras ir Mikelonas",
    "Senegalas",
    "Sent Kitsas ir Nevis",
    "Sent Lusija",
    "Sent Vinsentas ir Grenadinai",
    "Serbija",
    "Siera Leonė",
    "Sylendas",
    "Singapūras",
    "Sirija",
    "Slovakija",
    "Slovėnija",
    "Somalis",
    "Somalilandas",
    "Sudanas",
    "Suomija",
    "Surinamas",
    "Svalbardas",
    "Svazilandas",
    "Šiaurės Korėja",
    "Šri Lanka",
    "Šventoji Elena",
    "Švedija",
    "Šveicarija",
    "Tadžikija",
    "Tailandas",
    "Taivanas",
    "Tanzanija",
    "Terksas ir Kaikosas",
    "Tibetas",
    "Togas",
    "Tokelau",
    "Tonga",
    "Trinidadas ir Tobagas",
    "Tristanas da Kunja",
    "Tunisas",
    "Turkija",
    "Turkmėnija",
    "Turkų Kipras",
    "Tuvalu",
    "Uganda",
    "Ukraina",
    "Urugvajus",
    "Uzbekija",
    "Vakarų Sachara",
    "Vanuatu",
    "Vatikanas",
    "Velykų sala",
    "Venesuela",
    "Vengrija",
    "Vietnamas",
    "Vokietija",
    "Volisas ir Futuna",
    "Zambija",
    "Zimbabvė",
);

$gimtine = array(
    'Vilniaus m. sav.',
    'Kauno m. sav.',
    'Klaipėdos m. sav.',
    'Panevėžio m. sav.',
    'Šiaulių m. sav.',
    'Akmenės r. sav.',
    'Alytaus m. sav.',
    'Alytaus r. sav.',
    'Anykščių r. sav.',
    'Birštono sav.',
    'Biržų r. sav.',
    'Druskininkų sav.',
    'Elektrėnų sav.',
    'Ignalinos r. sav.',
    'Jonavos r. sav.',
    'Joniškio r. sav.',
    'Jurbarko r. sav.',
    'Kaišiadorių r. sav.',
    'Kalvarijos sav.',
    'Kazlų Rūdos sav.',
    'Kėdainių r. sav.',
    'Kelmės r. sav.',
    'Kretingos r. sav.',
    'Kupiškio r. sav.',
    'Lazdijų r. sav.',
    'Marijampolės sav.',
    'Mažeikių r. sav.',
    'Molėtų r. sav.',
    'Neringos sav.',
    'Pagėgių sav.',
    'Pakruojo r. sav.',
    'Palangos m. sav.',
    'Panevėžio r. sav.',
    'Pasvalio r. sav.',
    'Plungės r. sav.',
    'Prienų r. sav.',
    'Radviliškio r. sav.',
    'Raseinių r. sav.',
    'Rietavo sav.',
    'Rokiškio r. sav.',
    'Šakių r. sav.',
    'Šalčininkų r. sav.',
    'Šiaulių r. sav.',
    'Šilalės r. sav.',
    'Šilutės r. sav.',
    'Širvintų r. sav.',
    'Skuodo r. sav.',
    'Švenčionių r. sav.',
    'Tauragės r. sav.',
    'Telšių r. sav.',
    'Trakų r. sav.',
    'Ukmergės r. sav.',
    'Utenos r. sav.',
    'Varėnos r. sav.',
    'Vilkaviškio r. sav.',
    'Vilniaus r. sav.',
    'Visagino sav.',
    'Zarasų r. sav.',
);

$religija = array(
    'Krikščionybė', 
    'Islamas', 
    'Hinduizmas', 
    'Budizmas', 
    'Šintoizmas', 
    'Sikizmas', 
    'Judaizmas', 
    'Konfucianizmas',
    'Netikiu',
    'Kita',
);

$statusas = array(
    'Laisvas (-a)',
    'Turiu neipareigojančių santykių',
    'Įsipareigojęs (-usi)',
    'Vedęs (ištekėjusi)',
    'Vedęs (ištekėjusi) (negyvename kartu)',
    'Išsiskyręs (-usi)', 
    'Našlys (-ė)'
);

/////////

$issilavinimas = array(
    'Pagrindinis',
    'Vidurinis',
    'Profesinis',
    'Bakalauras',
    'Magistras',
    'Daktaras',
    'Profesorius',
    'Nesvarbu'
);

$pareigos = array(
    'Administravimas',
    'Apsauga',
    'Aptarnavimas',
    'Elektronika / Telekomunikacijos',
    'Energetika / Gamtosištekliai',
    'Finansai',
    'Informacija / Žiniasklaida',
    'Informacinėstechnologijos',
    'Maitinimas',
    'Marketingas / Reklama / RsV',
    'Mechanika / Inžinerija',
    'Pardavimai / Pirkimai',
    'Personalovaldymas / Mokymai',
    'Pramogos / Kultūra / Menai',
    'Pramonė / Gamyba',
    'Statyba / Nekilnojamasisturtas',
    'Sveikatosapsauga / Farmacija',
    'Švietimas / Moksliniaityrimai',
    'Teisė',
    'Transportas / Logistika',
    'Turizmas / Viešbučiai',
    'Vadovavimas / Verslovystymas',
    'Valstybinėtarnyba',
    'Žemėsūkis / Miškininkystė / Žuvininkystė',
    'Nesvarbu',
    'Kita',
);

$uzdarbis[0] = '< 500£'; 
for($i = 500; $i < 5000; $i = $i + 500){
    $uzdarbis[] = $i." - ". ($i+500)."£"; 
}
$uzdarbis[] = '> 5000£';
$uzdarbis[] = 'Nesvarbu';


$orentacija = array(
    'Biseksuali',
    'Heteroseksuali',
    'Homoseksuali',
);

$tikslas = array(
    'Rimti santykiai',
    'Trumpalaikiai santykiai',
    'Seksas',
    'Flirtas',
    'Slapti pasimatymai',
    'Susirašinėjimai',
    'Visi išvardinti'
);

///////////////////////////////

$ugis[] = '< 100cm'; 
for($i = 100; $i <= 220; $i++){
    $ugis[] = $i."cm"; 
}
$ugis[] = '> 220cm';  


$svoris[] = '< 40kg'; 
for($i = 40; $i <= 180; $i++){
    $svoris[] = $i."kg"; 
}
$svoris[] = '> 180kg'; 
$svoris[] = 'Nesvarbu';


$sudejimas = array(
    'Lieknas',
    'Vidutiniškas',
    'Atletiškas',
    'Pilnokas',
);


$plaukai = array(
    'Juoda',
    'Kaštoninė',
    'Pilka',
    'Ruda',
    'Šviesiai ruda',
    'Šviesi',
    'Žila',
    'Raudona', 
    'Melyna',
    'Kita'
);


$akys = array(
    'Mėlyna',
    'Ruda',
    'Pilka',
    'Žalia',
    'Pilkai rudos', 
    'Pilkai žalios', 
    'Žydros', 
    'Žaliai rudos', 
    'Gintaro',
    'Kita'
);


$stilius = array(
    "Romantinis",
    "Bohemiskas",
    "Dalykinis",
    "Provokuojantis",
    "Prancūziškas",
    "Klasikinis",
    "Avangardinis",
    "Sportinis",
    "Džinsai ir marškinėliai",
    "Laisvalaikio stilius",
    "Aukštoji mada",
    "Hippy",
    "R&B / RAP",
    "Metal / Rock",
    "Punk",
    "Gotiškas",
    "Emo",
    'Kita',
);

for($i = date('Y')-18; $i > date('Y') - 80; $i--){
    $year['a'.$i] = $i;
}
for($i = 1; $i <= 12; $i++){
    $month[$i] = $i;
}
for($i = 1; $i < 32; $i++){
    $day[$i] = $i;
}

for($i = 18; $i < 99; $i++)
    $amzius_tarp[] = $i;


?>